### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by Super1985** [madmurphy/cookies.js#3]
This a great library.  Thanks for creating this.  Do you mind dual-licensing this under MIT also, or changing to an MIT license?

https://opensource.org/licenses/MIT

I would like to use this on a few projects that I am working on, however we aren't allowed to use GPL software, for whatever reason.  Unfortunately, I don't have control over that decision.

Thanks for your help!

**Comment by madmurphy** [comment]
@Super1985

Really thank you for your words.

Regarding the MIT license, please try to understand my point. I do not work as a programmer – nor I want to. I program just in my free time. And when I do it, I always try – a very very little – to make this world a better world.

I think that the GPL license is not just any license, but is a great achievement for everyone. And if someone abandons the GPL in order to meet the needs of a particular person/entity/company/etc. he is giving away something belonging to everyone – not anymore more just to himself – to serve the interests of a particular group/person.

The MIT license, despite being open source, is not copyleft and approaches very closely the concept of “abandoning”. And personally I find it also quite primitive, both for the users – because it does not grant that all the efforts spent on an intellectual work will always remain free – and for the programmers – because it does not forbid others to capitalize their work.

So I am sorry to disappoint you… I would rather ask you to convince your boss to think differently about GPL software (at least when it is good software).

All the best,

-- madmurphy

**Comment by madmurphy** [comment]
@Super1985

Really thank you for your words.

Regarding the MIT license, please try to understand my point. I do not work as a programmer, nor I want to: I program just in my free time. And when I do it, I always try – a very very little – to make this world a better world.

I think that the GPL license is not just any license, but is a great achievement for everyone. And if someone abandons the GPL in order to meet the needs of a particular person/entity/company/etc. he is giving away something belonging to everyone – not anymore just to himself – to serve the interests of a particular group/person.

The MIT license, despite being open source, is not copyleft and approaches very closely the concept of “abandoning”. And personally I find it also quite primitive, both for the users – because it does not grant that all the efforts spent on an intellectual work will always remain free – and for the programmers – because it does not forbid others to capitalize their work.

So I am sorry to disappoint you… I would rather ask you to convince your boss to think differently about GPL software (at least when it is good software).

All the best,

— madmurphy

**Comment by Super1985** [comment]
I understand.  Thanks for your help.

**Comment by madmurphy** [comment]
You are welcome.
