### ISSUE TITLE
Compatibilitie problem with Internet Explorer (all versions) and the use of max-age.

### ISSUE THREAD

**Issue by lcrespilho** [madmurphy/cookies.js#5]
On setItem method, the use of _max-age_ isn't compatible with any version of Internet Explorer, Edge and a lot of Mobile browsers (as sugested by  [MDN Document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)).

Maybe you could alter line 37 with something like this:
`sExpires = vEnd === Infinity ? "; expires=Fri, 31 Dec 9999 23:59:59 GMT" : "; expires=" + new Date(new Date().getTime() + vEnd).toUTCString();`
that has full browser support.

Thanks a lot.
Best regards.

**Comment by madmurphy** [comment]
@lcrespilho

Thanx for opening this issue!

This library aims to abstract JavaScript's access to cookies, but does not aim to help good standards to become deprecated. The `max-age` parameter is a good parameter and is [a standard defined in rfc6265](https://tools.ietf.org/html/rfc6265#section-5.2.2). Nevertheless the lack of support in some browsers, as your comment attests, cannot be ignored.

After thinking a bit, I decided, instead of removing the library's internal usage of `max-age`, to explain the current situation and offer an easy solution [in a note in the MDN article](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie/Simple_document.cookie_framework#max-age_note) – which is the official documentation page of this library.

All the best!

**Comment by lcrespilho** [comment]
@madmurphy 
Thanks for your feedback. I just saw the note on MDN article and your argument sounds fair.

Thanks a lot.
Regards.
